### ISSUE TITLE
Difference between this and Cascadea

### ISSUE THREAD

**Issue by sn0wyfall** [fphilipe/PageExtender.app#12]
Hi! So Cascadea on the App Store is $2 vs $5 for this app. I was wondering what the differences were between the two? Of course, this is open source which is super cool, but I was wondering if there was anything else. 

Thank you for making this!

**Comment by FranklinYu** [comment]
This one does JavaScript. Cascadea is CSS only.

**Comment by fphilipe** [comment]
Just checked, [Cascadea](https://apps.apple.com/us/app/cascadea/id1432182561?mt=12) is $2.99. It has a proper UI for editing stylesheets, iCloud syncing, and [Stylus preprocessor](https://stylus-lang.com) support.

PageExtender is more of a hacker tool in the sense that it just loads so-called dotfiles from a specific location. It is a spiritual successor of dotcss and dotjs. For more on the history and motivation behind it, have a look at the [introductory blog post](https://phili.pe/posts/introducing-page-extender-for-safari/) I wrote, specifically the _History_ section.

Being more of a hacker tool, it expects a certain familiarity with CSS, JS, and editing text files in general. Thus, PageExtender might not be for everyone. Hence the disclaimer in the App Store description:

> **PLEASE NOTE**
>
> Basic web development skills are required for this extension to be useful, i.e. you should either know some CSS or JavaScript.

The price of $4.99 is what I deemed fair. It costs money to distribute apps on the App Store. Apple takes a 30% cut, thus each purchase (almost) buys me a coffee where I live (Zurich, Switzerland is an expensive place to live, if not the most expensive). But since I want this to be available for everybody, the source is freely distributed and you're more than welcome to compile it yourself 😊

**Comment by sn0wyfall** [comment]
Awesome! Thanks a lot for the info, and thanks again for making this! I can't imagine how you make money off of this when the people not that tech-savvy would go with Cascada, and the people who know dev stuff would likely be able to compile this from source, but I wish you the best of luck with this tool! It's super cool.

**Comment by gingerbeardman** [comment]
@sn0wyfall people who only want CSS changes have many other options. I use PE about 50/50 for JS/CSS, but the JS is the most important to me. 

As Philipe has said this extension was created to allow the much older dot file method to work in Safari. It's heritage is different to where you are coming from.
