### ISSUE TITLE
Possible to Perform CORS XML Requests?

### ISSUE THREAD

**Issue by mlturner88** [fphilipe/PageExtender.app#16]
Would it be possible to grab HTML from another webpage? As an example, I am trying to dynamically grab SVG elements from another website and insert them into a page. I believe in other extensions the extension itself could perform these requests on our behalf to get around the CORS issue. What are your thoughts? Thanks!

**Comment by fphilipe** [comment]
You can use everything that is at your disposal with JS. But as you say, CORS might be an issue.

I do not plan to add a mechanism to allow requests through the extension in order to workaround CORS, sorry.

Maybe you can set up a web service that acts as a proxy, allowing CORS, and relays the request. Maybe there already is such a service around.

Hope this helps.
