### ISSUE TITLE
Injecting JQuery

### ISSUE THREAD

**Issue by archer-party-city** [fphilipe/PageExtender.app#22]
I am attempting to inject JQuery into a page, and then subsequently use it, however I keep hitting an issue where it will not import it.

I've tried npm installing it within the js folder and including it (at which point it doesn't like the import) I've tried require'ing it, and it doesn't know "require"

I've tried the old, inject it into the header with getElementByTagName.  The element shows in the header, but I cannot access it with $ as it acts as though that is unknown.

An example of a correctly injected JQuery would be really appreciated!

**Comment by fphilipe** [comment]
The JavaScript that the extension loads is sent to the browser where it is `eval`ed:

https://github.com/fphilipe/PageExtender.app/blob/13ae7f3288097e5b28eb03fa2b2225df8dc84f66/Source/Extension/script.js#L22-L30

Thus, the script doesn't have access to the filesystem at all.

I'm afraid injecting jQuery also won't work. I've tried this:

```js
function injectScript(src) {
    return new Promise((resolve, reject) => {
        const script = document.createElement('script');
        script.src = src;
        script.addEventListener('load', resolve);
        script.addEventListener('error', e => reject(e.error));
        document.head.appendChild(script);
    });
}

injectScript('https://code.jquery.com/jquery-3.6.0.slim.min.js')
    .then(() => {
        console.log('Script loaded!');
        console.log(jQuery)
    }).catch(error => {
        console.error(error);
    });
```

The problem is that the evaluated script will simply not have access to the page's script environment as it is sandboxed. You will be able to use `jQuery` from the console, but the above `console.log(jQuery)` will fail.

What does work is something like this:

```js
fetch('https://code.jquery.com/jquery-3.6.0.slim.min.js')
  .then(response => response.text())
  .then(js => {
    eval(js)
    console.log(jQuery)
  })
```

What are you trying to accomplish though? [You might not need jQuery at all](https://youmightnotneedjquery.com).

**Comment by archer-party-city** [comment]
First, thank you for the very comprehensive answer.

I was just trying to find an "easy" way to grab specific nodes from horribly written web pages without having to write the equivalent VanillaJS to get it.

Regardless, you rock, best $5 I've spend recently!  👍 

The fetch version works perfectly, thank you!
